/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect} from 'react'
import {useAnimations, useGLTF} from '@react-three/drei'
import * as THREE from "three";
import ModalsInRooms from "../pages/tech-room/const/modals/in_room.tsx";
import StaticCollider from "../components/static-collider.tsx";

interface PremiumModelProps {
    position?: [number, number, number];
    rotation?: [number, number, number];
    scale?: [number, number, number];
}

interface GLTFResult extends THREE.Object3D {
    nodes: {
        [key: string]: THREE.Mesh;
    };
    materials: {
        [key: string]: THREE.Material;
    };
}

export function PremiumModel(props:PremiumModelProps) {
    const { nodes } = useGLTF('/models/PREMIUM.glb') as unknown as GLTFResult

    const doorAnimation = useGLTF("/animations/PREMIUM_DOOR.glb");
    const { animations: doorAnimations, scene: doorScene } = doorAnimation;
    const { actions: doorActions } = useAnimations(doorAnimations, doorScene);

    const floorAnimation = useGLTF("/animations/PREMIUM_FLOOR.glb");
    const { animations: floorAnimations, scene: floorScene } = floorAnimation;
    const { actions: floorActions } = useAnimations(floorAnimations, floorScene);

    useEffect(() => {
        if (doorActions?.Animation) {
            doorActions.Animation.play();
        }

    }, [doorActions]);

    useEffect(() => {
        if (floorActions?.Animation) {
            floorActions.Animation.play();
        }

    }, [floorActions]);


    const currentRoomData = ModalsInRooms.find((roomData) => roomData.name === 'PREMIUM');

    return (
        <group {...props} dispose={null}>
            {Object.entries(nodes).map(([key, node]) => {
                if (node instanceof THREE.Mesh) {
                    return (
                        <group key={node.name}>
                            <StaticCollider object={node} currentRoomData={currentRoomData} key={key}/>
                        </group>
                    );
                }
                return null;
            })}

            <primitive object={doorScene}/>
            <primitive object={floorScene}/>

        </group>
    );
}

// useGLTF.preload('/models/PREMIUM.glb')
// useGLTF.preload("/animations/PREMIUM_DOOR.glb");
// useGLTF.preload("/animations/PREMIUM_FLOOR.glb");
